### ISSUE TITLE
facing problem to convert input data into "list"

### ISSUE THREAD

**Issue by vishnuvardhan66** [CodeAbbey/meta#76]
sir/madam, I am facing problem to convert the input data into a list.... I have to go to every number and put comma after it and copy the next number from the bottom line and paste it beside number present in the first line... Is there any solution for this?? Even though the result is correct with brackets and commas it is showing as error. And if I want to try again, the input data will be changed and again I have to convert the whole input data in the form of list.. Please give me a solution for this because of this I am not getting interest to solve the problems in github. As I am a beginner in programming I have necessity to solve the problems in github to get better at programming.  Please I am urging you to show me a solution for my problem quickly

**Comment by RodionGork** [comment]
This repo is not for questions about how to solve this or that problem. Sorry. Use general forums for programming-related questions.
