### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by bileshg** [CodeAbbey/meta#77]
Whenever I try to log in from the [login page](https://www.codeabbey.com/index/login), I get the following error.

> ### Not Acceptable!
> An appropriate representation of the requested resource could not be found on this server. This error was generated by Mod_Security.

Screen capture:
![Region](https://user-images.githubusercontent.com/17637482/130265058-30e94969-80e4-476d-9e5d-2495762ee0bb.png)

**Comment by RodionGork** [comment]
Probably intermittent bug :( now I can't reproduce this

**Comment by bileshg** [comment]
I'm still not able to log in. Same error.

Also, the code abbey banner I used in my various other profiles (like StackOverflow) also doesn't work.

The following link returns nothing.

https://www.codeabbey.com/index/user_banner/bileshganguly.png

Was my account nuked? Because that would be really depressing; I had solved 70+ problems.

**Comment by bileshg** [comment]
After a long time, I was able to log in today... Everything looks ok except for the user banner which is not being displayed...
