### ISSUE TITLE
Password Recovery/Reset fails to send email

### ISSUE THREAD

**Issue by llowenthal** [CodeAbbey/meta#78]
The password recovery page hangs at a white screen upon entering email and username.

Refreshing the white page gives a warning about re-sending information and then the next screen says "Message was sent recently, please check your mailbox again (perhaps 'spam' folder?) or wait a bit if necessary..."

This has been an issue for approximately 3 days.

**Comment by RodionGork** [comment]
Shall check this, thanks... Sorry for delay.

**Comment by bileshg** [comment]
Maybe this is related to my issue ( #77 ) as well?

When I try to recover my account I get the following error.

> Not Acceptable!
> An appropriate representation of the requested resource could not be found on this server. This error was generated by Mod_Security.

**Comment by RodionGork** [comment]
Sorry for delay. Functionality restored. Regretfully it was due to my manual mistake - removed e-mail sending library when cleaning up files. Really sorry. Should work now, feel free to check.
