### ISSUE TITLE
Problem#2 loop in sum showing wrong answer

### ISSUE THREAD

**Issue by soudipnath** [CodeAbbey/meta#79]
I got this numbers 31 and 1029 ,124 ,965 ,910, 636 ,1271, 844 ,1238 ,594 ,202 ,304 ,442 ,990 ,553 ,694 ,32 ,300, 173 ,1177 ,715 ,362 ,1080 ,269 ,939 ,1022 ,604 ,1142 ,160 ,971 ,777, 255

this is my code
list_1 =[1029 ,124 ,965 ,910, 636 ,1271, 844 ,1238 ,594 ,202 ,304 ,442 ,990 ,553 ,694 ,32 ,300, 173 ,1177 ,715 ,362 ,1080 ,269 ,939 ,1022 ,604 ,1142 ,160 ,971 ,777, 255]

list_sum = 31
for num in list_1:
    list_sum = list_sum + num
print(list_sum)

this is my answer : 20805

but it still showing the wrong answer. it's happening every time with every number.
please do some this or let me know if I'm doing something wrong

**Comment by RodionGork** [comment]
This repo is not for questions on why your program doesn't work, sorry. This problem was solved by thousands of people so it is unlikely to be site's bug.
